services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myblog
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - HASURA_GRAPHQL_ENDPOINT=http://hasura:8080
    depends_on:
      - db
      - hasura

  db:
    image: postgres:15
    container_name: myblog-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.35.0
    container_name: myblog-hasura
    ports:
      - '8080:8080'
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=myadminsecretkey
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
